# Generated by Django 4.2.14 on 2025-11-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details_voyage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu', models.IntegerField(default=0, help_text='prix unitaire categorie = tarification', verbose_name='tarification elementaire pour une categorie')),
                ('designation_tarififcation', models.CharField(help_text='designation Tarififcation', max_length=10, verbose_name='designation')),
                ('slug', models.SlugField(default='02KJHMSLRTarififcationooopp8225hgqgqgnndnenxxxjk//5', max_length=100)),
                ('id_details_voyage', models.ForeignKey(help_text='id du voyage', on_delete=django.db.models.deletion.CASCADE, to='details_voyage.details_voyage')),
            ],
        ),
    ]
