# Generated by Django 4.2.14 on 2025-11-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train', '0003_alter_train_couleur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_depart', models.TimeField()),
                ('date_depart', models.DateField()),
                ('slug', models.SlugField(default='02Kkjsdhjfhf655qqzasjqsdbbbz555sc6JHMSLR', max_length=100)),
                ('id_train', models.ForeignKey(help_text="numero d'un train exemple A-0000 qui effectuer un voyage", on_delete=django.db.models.deletion.CASCADE, to='train.train', verbose_name="numero d'un train exemple A-0000 qui effectuer un voyage")),
            ],
        ),
    ]
