# Generated by Django 4.2.14 on 2025-11-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details_voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text="distance entre la gare de depart et d'arrivée", verbose_name="distance entre la gare de depart et d'arrivée")),
                ('slug', models.SlugField(default='distanceGareLPPZNN025SN02Kkjsdhjfhf655qqzasjqsdbbbz555sc6JHMSLR', max_length=100)),
                ('id_gare_arrive', models.ForeignKey(help_text="id dela Gare d'arrivee", on_delete=django.db.models.deletion.CASCADE, related_name='voyages_a_larrivee', to='gare.gare')),
                ('id_gare_depart', models.ForeignKey(help_text='id dela Gare de part', on_delete=django.db.models.deletion.CASCADE, related_name='voyages_au_depart', to='gare.gare')),
            ],
        ),
    ]
