# Generated by Django 4.2.14 on 2025-11-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details_voyage', '0001_initial'),
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_voyage',
            name='id_voyage',
            field=models.ForeignKey(help_text='id du voyage', on_delete=django.db.models.deletion.CASCADE, to='voyage.voyage'),
        ),
    ]
