# Generated by Django 4.2.14 on 2025-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_voyage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_voyage',
            name='image',
            field=models.ImageField(default='', upload_to='gares_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details_voyage',
            name='distance',
            field=models.IntegerField(blank=True, help_text="distance entre la gare de depart et d'arrivée", null=True, verbose_name="distance entre la gare de depart et d'arrivée"),
        ),
    ]
