# Generated by Django 4.2.14 on 2025-11-25 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode_paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paiement', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.BooleanField(blank=True, null=True)),
                ('id_mode_paiement', models.ForeignKey(blank=True, help_text='le mode de paiement', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation_paiement.mode_paiement')),
                ('id_tarification', models.ForeignKey(help_text='id du categorie', on_delete=django.db.models.deletion.CASCADE, to='tarification.tarification')),
                ('id_user', models.ForeignKey(help_text='id du train', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
