# Generated by Django 4.2.14 on 2025-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_paiement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='qr_code',
            field=models.ImageField(blank=True, default='', null=True, upload_to='gares_images/'),
        ),
    ]
