# Generated by Django 4.2.14 on 2025-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_paiement', '0002_paiement_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='nombre_place_reserve',
            field=models.IntegerField(default=1),
        ),
    ]
