# Generated by Django 4.2.14 on 2025-11-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_paiement', '0003_paiement_nombre_place_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_billet',
            field=models.CharField(blank=True, default='XXXXXXXX', help_text='numero unique du billet', max_length=100, null=True, verbose_name='numero unique du billet'),
        ),
    ]
