# Generated by Django 4.2.14 on 2025-12-14 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation_paiement', '0004_paiement_numero_billet'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='email_user',
            field=models.EmailField(blank=True, default='boazkalonji962@gmail.com', help_text='email du user', max_length=200),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='id_user',
            field=models.ForeignKey(help_text='id du user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
