# Generated by Django 4.2.14 on 2025-12-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_paiement', '0005_paiement_email_user_alter_paiement_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='email_user',
            field=models.CharField(blank=True, default='boazkalonji962@gmail.com', help_text='email du user', max_length=200),
        ),
    ]
