# Generated by Django 4.2.14 on 2025-11-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication_avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_avis', models.CharField(help_text='reference_avis', max_length=100, verbose_name='reference_avis ')),
                ('titre_avis', models.CharField(help_text='titre_avis', max_length=100, verbose_name='titre_avis')),
                ('message_avis', models.CharField(help_text='message_avis', max_length=200, verbose_name='message_avis')),
                ('date_avis', models.DateField()),
                ('consigne_avis', models.CharField(help_text='consigne_avis', max_length=200, verbose_name='consigne_avis')),
                ('slug', models.SlugField(default='jkjkhjdhjdhjzhjezjkoiuehb5kskhjbvbzhj5685dhhzehjjkehjzhjehhjcncjkzzjkzoiioeuiuirhcbzbnklqkdhshdbbb', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pubilaction_tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='jkjkhjdhjdhjzhjezjkoiuehb5kskhjbvbzhj5685dhhzehjjkehjzhjehhjcncjkzzjkzoiioeuiuirhcbzbnklqkdhshdbbb', max_length=100)),
                ('id_pubilaction_avis', models.ForeignKey(help_text='id dela Publication_avis', on_delete=django.db.models.deletion.CASCADE, to='publication_avis.publication_avis')),
                ('id_tarification', models.ForeignKey(help_text='id dela Tarification', on_delete=django.db.models.deletion.CASCADE, to='tarification.tarification')),
            ],
        ),
    ]
