# Generated by Django 4.2.14 on 2025-12-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_avis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication_avis',
            name='consigne_avis',
            field=models.TextField(help_text='consigne_avis', verbose_name='consigne_avis'),
        ),
        migrations.AlterField(
            model_name='publication_avis',
            name='message_avis',
            field=models.TextField(help_text='message_avis', verbose_name='message_avis'),
        ),
        migrations.AlterField(
            model_name='publication_avis',
            name='reference_avis',
            field=models.TextField(help_text='reference_avis', verbose_name='reference_avis '),
        ),
        migrations.AlterField(
            model_name='publication_avis',
            name='titre_avis',
            field=models.TextField(help_text='titre_avis', verbose_name='titre_avis'),
        ),
    ]
