# Generated by Django 4.2.14 on 2025-11-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_gare', models.CharField(help_text='rlibelle du gare', max_length=20, verbose_name='libelle du gare')),
                ('ville_gare', models.CharField(help_text='ville du gare', max_length=20, verbose_name='ville du gare')),
                ('slug', models.SlugField(default='02Kkjsdhjfhf655qqzasjqsdbbbz555sc6JHMSLR', max_length=100)),
            ],
        ),
    ]
