# Generated by Django 4.2.14 on 2025-11-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_train', models.CharField(blank=True, help_text='un sert de clé secondaire à la table voiture', max_length=10, null=True, verbose_name='numero voiture exemple A-0000')),
            ],
        ),
    ]
