# Generated by Django 4.2.14 on 2025-11-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='couleur',
            field=models.CharField(default='pas de couleur', help_text='couleur', max_length=30, verbose_name='couleur'),
        ),
        migrations.AddField(
            model_name='train',
            name='slug',
            field=models.SlugField(default='02Kkjsdhjfhf655qqzasjqsdbbbz555sc6JHMSLR', max_length=100),
        ),
        migrations.AddField(
            model_name='train',
            name='taille_ram',
            field=models.IntegerField(default=0, help_text='taille_ram', verbose_name='taille_ram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='train',
            name='numero_train',
            field=models.CharField(default=1, help_text='un sert de clé secondaire à la table voiture', max_length=10, verbose_name='numero voiture exemple A-0000'),
            preserve_default=False,
        ),
    ]
