# Generated by Django 4.2.14 on 2025-11-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_train_couleur_train_slug_train_taille_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='couleur',
            field=models.CharField(default='pas de couleur', help_text='couleur', max_length=30, verbose_name='couleur'),
        ),
    ]
