# Generated by Django 4.2.14 on 2025-11-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train', '0001_initial'),
        ('traino_materiel', '0003_rename_tarification_categorie_tarif_categorie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_voiture', models.CharField(blank=True, help_text='un sert de clé secondaire à la table voiture', max_length=10, null=True, verbose_name='numero voiture exemple A-0000')),
                ('slug', models.SlugField(default='02Kkjsdhjfhf655qqzasjqsdbbbz555sc6JHMSLR', max_length=100)),
                ('id_categorie', models.ForeignKey(help_text='id du categorie', on_delete=django.db.models.deletion.CASCADE, to='traino_materiel.categorie')),
                ('id_train', models.ForeignKey(help_text='id du train', on_delete=django.db.models.deletion.CASCADE, to='train.train')),
            ],
        ),
    ]
