# Generated by Django 4.2.14 on 2025-11-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarification', '0001_initial'),
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='id_categorie',
        ),
        migrations.AddField(
            model_name='voiture',
            name='id_tarification',
            field=models.ForeignKey(default=1, help_text='id du categorie', on_delete=django.db.models.deletion.CASCADE, to='tarification.tarification'),
            preserve_default=False,
        ),
    ]
