# Generated by Django 4.2.14 on 2025-11-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0002_remove_voiture_id_categorie_voiture_id_tarification'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='nombre_place',
            field=models.IntegerField(default=0),
        ),
    ]
