# Generated by Django 4.2.14 on 2025-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_categorie', models.CharField(help_text='designation categorie', max_length=10, verbose_name='designation')),
            ],
        ),
    ]
