# Generated by Django 4.2.14 on 2025-11-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino_materiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='tarification',
            field=models.IntegerField(default=0, help_text='prix unitaire categorie = tarification', verbose_name='tarification total pour une categorie'),
        ),
    ]
