# Generated by Django 4.2.14 on 2025-11-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino_materiel', '0002_categorie_tarification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='tarification',
            new_name='tarif',
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(default='02KJHMSLR', max_length=100),
        ),
    ]
